#pragma config(Sensor, S2,     distance,       sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		while(true){
			displayTextLine(1, "distance: %f", sensorValue[distance]);
			wait1Msec(500);
		}
}
