#pragma config(Sensor, S1,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int oldSensorVal=SensorValue[lightSensor];
	int desiredMin=40;
	int desiredMax=60;
	int prevError=0;
	int defaultPower = 35;
	int turnPower = 15;
	int powerL;
	int powerR;
	int error;
	int turn;
	int whiteCounter;
	int turnTime = 25;  //in miliseconds
	int blackThreshold = 150;
	float k= 8;

	int blackTime = 0;

	int currSensorVal;
	while(true){
		currSensorVal=SensorValue[lightSensor];
		if ((desiredMin <= currSensorVal) && ( currSensorVal <= desiredMax)) {
		  error = 0;
		  blackTime = 0;
	  } else if (currSensorVal < desiredMin) {
	    error = currSensorVal - desiredMin;
	    blackTime++;
	  } else {
	    error = currSensorVal - desiredMax;
	    blackTime = 0;
	  }
		turn=(int)(k*((float)error));

		if (blackTime > blackThreshold) {
			powerR = -50;
			powerL = 10;
			motor[left]=powerL;
	  	motor[right]=powerR;
	  	wait1Msec(turnTime);
	  	motor[left]=defaultPower;
	  	motor[right]=defaultPower;
	  	whiteCounter = 0;
	  	while ((SensorValue[lightSensor] > desiredMax) &&(whiteCounter <= 250)) {
	  		whiteCounter++;
	  	}
	  	continue;
		} else{
		  if (turn == 0) {
			  powerR = defaultPower;
			  powerL = defaultPower;
	    } else if (turn > 0) {
	  	  powerR=turnPower+turn;
	  	  //powerL=0;
	  	  powerL=turnPower-turn;
	    } else {
	      //powerR=0;
	    	powerR=turnPower+turn;
	  	  powerL=turnPower-turn;
	    }
	  }
	  displayTextLine(4, " %d  ", blackTime);
		motor[left]=powerL;
		motor[right]=powerR;
		prevError=error;
		oldSensorVal=currSensorVal;

	}

}
