#pragma config(Motor,  motorA,          Arm1,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Arm2,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotArm2.c"
#include "waveFrontDir2.c"

float XA = 3.75;
float YA = 2.5;

float XB;
float YB;

float goalDeg1;
float goalDeg2;

float goalCol;
float goalRow;

float startRow = 0;
float startCol = 0;


path pathArray;

void goToTarget(float X, float Y)
{
	////    SETUP //////////////////////////////////

	//CHANGE THIS TO CHECK WHETHER THESE ARE VALID
	float goalRad2 = (getGoalDegree2(X, Y, true);
	float goalRad1 = getGoalDegree1(X, Y, goalDeg2);

	goalDeg1 = radiansToDegrees(goalRad1);
	goalDeg2 = radiansToDegrees(goalRad2);
	//CHANGE THIS TO CHECK WHETHER THESE ARE VALID

	goalCol = fromDegreesToBox(goalDeg1);
	goalRow = fromDegreesToBox(goalDeg2);

	calcPath(&pathArray, goalRow, goalCol, startRow, startCol);

	///////////// END SETUP///////////////////////////

	int i = 0;
	while( i < pathArray.pathLength){
		int theta1 = fromBoxToDegrees(pathArray.waypoints[i].c);
		int theta2 = fromBoxToDegrees(pathArray.waypoints[i].r);
		goToDegree(theta1, theta2);
		i = i + 1;
	}

	goToExactGoal(goalDeg1, goalDeg2);

	startRow = goalRow;
	startCol = goalCol;
}

task main{
	nMotorEncoder[Arm1] = 0;
	nMotorEncoder[Arm2] = 180;

	goToTarget(XA, YA);
}
