#pragma config(Motor,  motorA,          Arm1,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Arm2,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "robotArm2.c"
#include "waveFrontDir2.c"

float XA;
float YA;

float XB;
float YB;

float goalDeg1;
float goalDeg2;

float goalCol;
float goalRow;

float startRow = 0;
float startCol = 0;


path pathArray;

void goToTarget(float X, float Y)
{
	nMotorEncoder[Arm1] = 0;
	nMotorEncoder[Arm2] = 0;
	////    SETUP //////////////////////////////////

	//CHANGE THIS TO CHECK WHETHER THESE ARE VALID
	goalDeg2 = getGoalDegree2(X, Y, true);
	goalDeg1 = getGoalDegree1(X, Y, goalDeg2);
	//CHANGE THIS TO CHECK WHETHER THESE ARE VALID

	goalCol = fromRadianToBox(goalDeg1);
	goalRow = fromRadianToBox(goalDeg2);

	calcPath(&pathArray, goalRow, goalCol, startRow, startCol);

	///////////// END SETUP///////////////////////////

	nMotorEncoder[Arm1] = 0;
	nMotorEncoder[Arm2] = 0;

	int i = 0;
	while( i < pathArray.pathLength){
		int theta1 = fromBoxToRadian(pathArray.waypoints[i].c);
		int theta2 = fromBoxToRadian(pathArray.waypoints[i].r);
		goToDegree(theta1, theta2);
		i = i + 1;
	}

	goToExactGoal(goalDeg1, goalDeg2);

	startRow = goalRow;
	startCol = goalCol;
}

task main{
	nMotorEncoder[Arm1] = 0;
	nMotorEncoder[Arm2] = 0;

	goToTarget(XA, YA);
}
